export default {
  GAME_PHASE_WAITING: 'GAME_WAITING',
  GAME_PHASE_DEAL_1: 'DEAL_1',
  GAME_PHASE_DEAL_2: 'DEAL_2',
  GAME_PHASE_DEAL_3: 'DEAL_3',
  GAME_PHASE_DEAL_4: 'DEAL_4',
  GAME_PHASE_REMEMBER_CARDS: 'REMEMBER_CARDS',
  GAME_PHASE_PLAY: 'PHASE_PLAY',

  GAME_REQUEST_DEAL_1: 'DEAL_1_REQUEST',
  GAME_DEAL_1_RED: 'DEAL_1_RESPONSE_RED',
  GAME_DEAL_1_BLACK: 'DEAL_1_RESPONSE_BLACK',
  GAME_RESPONSE_DEAL_1: 'DEAL_1_RESPONSE',

  GAME_REQUEST_DEAL_2: 'DEAL_2_REQUEST',
  GAME_DEAL_2_MORE: 'DEAL_2_MORE',
  GAME_DEAL_2_LESS: 'DEAL_2_LESS',
  GAME_RESPONSE_DEAL_2: 'DEAL_2_RESPONSE',


  GAME_REQUEST_DEAL_3: 'DEAL_3_REQUEST',
  GAME_DEAL_3_INSIDE: 'DEAL_3_INSIDE',
  GAME_DEAL_3_OUTSIDE: 'DEAL_3_OUTSIDE',
  GAME_RESPONSE_DEAL_3: 'DEAL_3_RESPONSE',


  GAME_REQUEST_DEAL_4: 'DEAL_4_REQUEST',
  GAME_RESPONSE_DEAL_4: 'DEAL_4_RESPONSE',

  GAME_UPDATE_USER_JOINED: 'USER_JOINED',
  GAME_UPDATE_GAME_PHASE: 'NEW_GAME_PHASE',
  GAME_UPDATE_NEW_CARD: 'NEW_CARD',

  CARD_SUIT_HEART: 'SUIT_HEART',
  CARD_SUIT_SPADE: 'SUIT_SPADE',
  CARD_SUIT_DIAMOND: 'SUIT_DIAMOND',
  CARD_SUIT_CLUB: 'SUIT_CLUB',

  CARD_SUITS: [
    'SUIT_HEART',
    'SUIT_SPADE',
    'SUIT_DIAMOND',
    'SUIT_CLUB',
  ],

  SECONDS_TO_REMEMBER: 10,

}
